# Generated by Django 4.0.6 on 2022-07-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trybe_api', '0002_authtokentoken_authuser_alter_goal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='trybe_api.authuser'),
        ),
        migrations.DeleteModel(
            name='Supporter',
        ),
        migrations.AddField(
            model_name='messages',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trybe_api.goal'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trybe_api.authuser'),
        ),
        migrations.AddField(
            model_name='invitedsupporter',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_supporters', to='trybe_api.goal'),
        ),
        migrations.AddField(
            model_name='acceptedsupporter',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_supporters', to='trybe_api.goal'),
        ),
        migrations.AddField(
            model_name='acceptedsupporter',
            name='supporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_supporters', to='trybe_api.authuser'),
        ),
    ]
